// <auto-generated />
namespace CoffeeFinder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixingRateandupdatingMenuclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingRateandupdatingMenuclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202107101424130_Fixing Rate and updating Menu class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
