// <auto-generated />
namespace CoffeeFinder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixingMenuControllersIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingMenuControllersIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "202107121316126_Fixing Menu Controllers Index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
